# Generated by Django 4.2.7 on 2023-11-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_emtry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emtry',
            name='text_2',
        ),
    ]
